PS2030
POLITICAL ANALYSIS

WEEK 13:  DIFFERENCE-IN-DIFFERENCE MODELS

EXAMPLE:  KENYA CIVIC EDUCATION DATA (FOLLOWING FINKEL&SMITH 2011, AJPS)

//USE KENYA 2 WAVE "WIDE" DATA

*tabulations of treatment variables
tab1 newtreat_ww0 newtreat_ww1
**tabulations of knowlege variables
tab1 know_w0 know_w1
sum know_w0 know_w1
*generate difference scores
gen knowdif=know_w1-know_w0
gen treatdif=newtreat_ww1-newtreat_ww0
tab1 treatdif knowdif

**THE BASIC FD MODEL
regress knowdif treatdif
regress knowdif newtreat_ww1  // SAME THING

***MARGINAL PREDICTIONS
tabstat know_w1 know_w0, by(treatdif)

****CONTROL GOES FROM 2.17 TO 2.55, WORKSHOP GOES FROM 2.37 TO 3
****SO DIFFERENCE FOR CONTROL IS .38, DIFFERENCE FOR WORKSHOP IS .63
****SO DIFFERENCE IN DIFFERENCE IS .25



*****ALTERNATIVE DiD ESTIMATION WITH LONG DATA

// USE KENYA 2 WAVE "LONG" DATA
xtset id _j // TELLS STATA THAT ID IS THE CASE MARKER AND _J IS THE TIME MARKER
reg know_w treat##_j  //REGRESSION OF KNOWLEDGE WITH TREATMENT GROUP, TIME, AND INTERACTION BETWEEN TREATMENT AND TIME

//RECOVERS THE EFFECT OF TIME AS .38 (FOR THE CONTROL GROUP)
//AND .38+.25 = .63 (FOR THE TREATMENT GROUP)
//SO DIFFERENCE-IN-DIFFERENCE OF .25, WHICH IS THE INTERACTION EFFECT BETWEEN TREATMENT AND TIME
//(AND THE .19 'TREAT' EFFECT IS THE WAVE 1 DIFFERENCE BETWEEN TREATMENT AND CONTROL)

*OR -- 'FIXED EFFECT' MODEL WHICH IS STANDARD FOR MULTIWAVE (N>2) PANEL ANALYSIS
xtreg know_w newtreat_ww _j, fe
